# Generated by Django 5.0.2 on 2024-03-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ajay", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="greet",
        ),
        migrations.AddField(
            model_name="home",
            name="greet2",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="about",
            name="heading",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="home",
            name="greet1",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="home",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
